### ISSUE TITLE
JEST test setLayoutAnimationEnabledExperimental is not a function error.

### ISSUE THREAD

**Issue by Kjaer** [renrizzolo/react-native-sectioned-multi-select#218]
this is the console output when I try to render sectioned multi list component on node.js / jest environment:
```sh
TypeError: _reactNative.UIManager.setLayoutAnimationEnabledExperimental is not a function

      at new RowItem (node_modules/react-native-sectioned-multi-select/lib/components/RowItem.js:22:17)
      at constructClassInstance (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3629:18)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7558:5)
      at beginWork$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9043:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12649:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12622:22)
      at callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12333:9)
      at eventHandler (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1825:24)
      at Scheduler_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1775:10)
```

I am currently investigating the issue and left mark here, in some case people got stuck may reference this issue.

**Comment by Kjaer** [comment]
Here is my deps at this time of writing:

```json
    "react": "^16.14.0",
    "react-native": "^0.63.3",
    "react-native-sectioned-multi-select": "^0.8.0",
    "@babel/core": "^7.12.3",
    "@babel/eslint-parser": "^7.12.1",
    "@babel/eslint-plugin": "^7.12.1",
    "@babel/preset-env": "^7.12.1",
    "@babel/runtime": "^7.12.1",
    "@testing-library/jest-native": "^3.4.3",
    "@testing-library/react-native": "^7.1.0",
    "babel-jest": "^26.6.2",
    "jest": "^26.6.2",
    "metro-react-native-babel-preset": "^0.63.0",
    "react-test-renderer": "^16.14.0"
```

**Comment by Kjaer** [comment]
https://github.com/renrizzolo/react-native-sectioned-multi-select/blob/d33fcb1a9a00a7d80735badedfd63bed089bfe68/lib/components/RowItem.js#L22

This is line cause the jest fail

**Comment by Kjaer** [comment]
Oh I am using node.js `15.0.1` and `npm `7.x`

**Comment by Kjaer** [comment]
with #219 this issue is no longer be problem
